lxd latest/stable

diff --git a/.github/workflows/pull_request.yaml b/.github/workflows/pull_request.yaml
--- a/.github/workflows/pull_request.yaml
+++ b/.github/workflows/pull_request.yaml
@@ -33,7 +33,7 @@ jobs:
                   sudo snap install charmcraft --channel=latest/stable --classic
             - name: "Install lxd"
               run: |
-                  sudo snap refresh lxd || echo "Failed refreshing LXD"
+                  sudo snap refresh lxd --channel=latest/stable || echo "Failed refreshing LXD"
                   echo "LXD version: $(lxd --version)"
             - name: "Configure lxd"
               run: |
